# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pipeline.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'pipeline.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0epipeline.proto\x12\rimagepipeline\"\x1a\n\x0bPingRequest\x12\x0b\n\x03seq\x18\x01 \x01(\x05\"\x18\n\tPingReply\x12\x0b\n\x03seq\x18\x01 \x01(\x05\"?\n\x04Mask\x12\t\n\x01w\x18\x01 \x01(\x05\x12\t\n\x01h\x18\x02 \x01(\x05\x12\r\n\x05score\x18\x03 \x01(\x02\x12\x12\n\npackedbits\x18\x04 \x01(\x0c\"Y\n\x12SegTrackingRequest\x12\x0f\n\x07\x61pi_key\x18\x01 \x01(\t\x12\x0e\n\x06prompt\x18\x02 \x01(\t\x12\x0b\n\x03rgb\x18\x03 \x01(\x0c\x12\x15\n\rbox_threshold\x18\x04 \x01(\x02\"E\n\x10SegTrackingReply\x12\"\n\x05masks\x18\x01 \x03(\x0b\x32\x13.imagepipeline.Mask\x12\r\n\x05label\x18\x02 \x03(\t2\xad\x01\n\x12ImageModelPipeline\x12>\n\x04Ping\x12\x1a.imagepipeline.PingRequest\x1a\x18.imagepipeline.PingReply\"\x00\x12W\n\x0bSegTracking\x12!.imagepipeline.SegTrackingRequest\x1a\x1f.imagepipeline.SegTrackingReply\"\x00(\x01\x30\x01\x42\x08P\x01\xa2\x02\x03HLWb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pipeline_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001\242\002\003HLW'
  _globals['_PINGREQUEST']._serialized_start=33
  _globals['_PINGREQUEST']._serialized_end=59
  _globals['_PINGREPLY']._serialized_start=61
  _globals['_PINGREPLY']._serialized_end=85
  _globals['_MASK']._serialized_start=87
  _globals['_MASK']._serialized_end=150
  _globals['_SEGTRACKINGREQUEST']._serialized_start=152
  _globals['_SEGTRACKINGREQUEST']._serialized_end=241
  _globals['_SEGTRACKINGREPLY']._serialized_start=243
  _globals['_SEGTRACKINGREPLY']._serialized_end=312
  _globals['_IMAGEMODELPIPELINE']._serialized_start=315
  _globals['_IMAGEMODELPIPELINE']._serialized_end=488
# @@protoc_insertion_point(module_scope)
