# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import pipeline_pb2 as pipeline__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in pipeline_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ImageModelPipelineStub(object):
    """Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/imagepipeline.ImageModelPipeline/Ping',
                request_serializer=pipeline__pb2.PingRequest.SerializeToString,
                response_deserializer=pipeline__pb2.PingReply.FromString,
                _registered_method=True)
        self.SegTracking = channel.stream_stream(
                '/imagepipeline.ImageModelPipeline/SegTracking',
                request_serializer=pipeline__pb2.SegTrackingRequest.SerializeToString,
                response_deserializer=pipeline__pb2.SegTrackingReply.FromString,
                _registered_method=True)


class ImageModelPipelineServicer(object):
    """Service definition
    """

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SegTracking(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageModelPipelineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=pipeline__pb2.PingRequest.FromString,
                    response_serializer=pipeline__pb2.PingReply.SerializeToString,
            ),
            'SegTracking': grpc.stream_stream_rpc_method_handler(
                    servicer.SegTracking,
                    request_deserializer=pipeline__pb2.SegTrackingRequest.FromString,
                    response_serializer=pipeline__pb2.SegTrackingReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'imagepipeline.ImageModelPipeline', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('imagepipeline.ImageModelPipeline', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ImageModelPipeline(object):
    """Service definition
    """

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/imagepipeline.ImageModelPipeline/Ping',
            pipeline__pb2.PingRequest.SerializeToString,
            pipeline__pb2.PingReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SegTracking(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/imagepipeline.ImageModelPipeline/SegTracking',
            pipeline__pb2.SegTrackingRequest.SerializeToString,
            pipeline__pb2.SegTrackingReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
