syntax = "proto3";

package imagepipeline;

option java_multiple_files = true;
option objc_class_prefix = "HLW";

// Ping-related messages
message PingRequest {
    int32 seq = 1;
  }
  
  message PingReply {
    int32 seq = 1;
  }
  
  // Mask-related messages
  message Mask {
    int32 w = 1;
    int32 h = 2;
    float score = 3;
    bytes packedbits = 4;
  }
  
  // Request message for pose detection using point cloud
  message SegTrackingRequest {
    string api_key = 1;
    string prompt = 2;
    bytes rgb = 3;
    float box_threshold = 4;
  }
  
  // Reply message for pose detection
  message SegTrackingReply {
    repeated Mask masks = 1;
    repeated string label = 2;
  }

// Service definition
service ImageModelPipeline {
    rpc Ping(PingRequest) returns (PingReply) {}
    rpc SegTracking(stream SegTrackingRequest) returns (stream SegTrackingReply) {}
}